server:
  listen_addr: 0.0.0.0:5001
global:
  logging: warn
  chainID: "0x88bb0" # hoodi
  ssh:
    private_key_path: $HOME/.ssh/id_rsa
    private_key_passphrase_path: "$HOME/.ssh/id_rsa.passphrase"
    known_hosts_path: $HOME/.ssh/known_hosts
    ignore_host_key: false
    use_agent: false
  database:
    path: snapshots-hoodi.db
  snapshots:
    check_interval_seconds: 1
    block_interval: 10 # 600 = 2h
    run_once: false
    dry_run: true
    cleanup:
      enabled: true
      keep_count: 3
      check_interval_hours: 24
    s3:
      bucket_name: "ethpandaops-ethereum-node-snapshots"
      region: "us-east-1"
      endpoint: "https://nyc3.digitaloceanspaces.com"
    rclone:
      version: "1.65.2"
      env:
        RCLONE_CONFIG_MYS3_TYPE: s3
        RCLONE_CONFIG_MYS3_PROVIDER: DigitalOcean
        RCLONE_CONFIG_MYS3_ACL: public-read
targets:
  ssh:
    - alias: "geth"
      host: "1.2.3.4"
      user: "devops"
      port: 22
      data_dir: /data/hoodi/geth/geth
      upload_prefix: hoodi/geth
      docker_containers:
        engine_snooper: snooper-engine
        execution: execution
        beacon: beacon
      endpoints:
        beacon: http://localhost:5052
        execution: http://localhost:8545
    - alias: "nethermind"
      host: "1.2.3.5"
      user: "devops"
      port: 22
      data_dir: /data/hoodi/nethermind/nethermind_db
      upload_prefix: hoodi/nethermind
      docker_containers:
        engine_snooper: snooper-engine
        execution: execution
        beacon: beacon
      endpoints:
        beacon: http://localhost:5052
        execution: http://localhost:8545
