global:
  logging: warn
  chainID: "0x4268" # Holesky
  ssh:
    private_key_path: $HOME/.ssh/id_rsa
    private_key_passphrase_path: "$HOME/.ssh/id_rsa.passphrase"
    known_hosts_path: $HOME/.ssh/known_hosts
    ignore_host_key: false
    use_agent: false
  snapshots:
    check_interval_seconds: 1
    block_interval: 100000 # 600 = 2h
    run_once: true
    rclone:
      version: "1.65.2"
      env:
        RCLONE_CONFIG_MYS3_TYPE: s3
        RCLONE_CONFIG_MYS3_PROVIDER: DigitalOcean
        RCLONE_CONFIG_MYS3_ACL: public-read
        RCLONE_CONFIG_MYS3_ENDPOINT: $S3_ENDPOINT_URL
        RCLONE_CONFIG_MYS3_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        RCLONE_CONFIG_MYS3_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      entrypoint: /bin/sh
      cmd_template: >-
        -ac "
        apk add --no-cache tar zstd &&
        cd {{ .DataDir }} &&
        tar -I zstd -cvf - .
        --exclude=./nodekey
        --exclude=./key
        --exclude=./discovery-secret
        | rclone rcat --s3-chunk-size 150M mys3:/{{ .UploadPathPrefix }}/snapshot.tar.zst &&
        rclone copy {{ .DataDir }}/_snapshot_eth_getBlockByNumber.json mys3:/{{ .UploadPathPrefix }} &&
        rclone copy {{ .DataDir }}/_snapshot_web3_clientVersion.json mys3:/{{ .UploadPathPrefix }}
        "
targets:
  ssh:
    - alias: "geth"
      host: "192.168.10.100"
      user: "devops"
      port: 22
      data_dir: /data/geth/geth
      upload_prefix: ethereum-node-snapshots/holesky/geth/latest
      docker_containers:
        engine_snooper: snooper-engine
        execution: execution
      endpoints:
        beacon: http://localhost:5052
        execution: http://localhost:8545
    - alias: "nethermind"
      host: "192.168.10.101"
      user: "devops"
      port: 22
      data_dir: /data/nethermind/nethermind_db
      upload_prefix: ethereum-node-snapshots/holesky/nethermind/latest
      docker_containers:
        engine_snooper: snooper-engine
        execution: execution
      endpoints:
        beacon: http://localhost:5052
        execution: http://localhost:8545
