global:
  logging: warn
  chainID: "0x4268" # Holesky
  ssh:
    private_key_path: $HOME/.ssh/id_rsa
    private_key_passphrase_path: "$HOME/.ssh/id_rsa.passphrase"
    known_hosts_path: $HOME/.ssh/known_hosts
    ignore_host_key: false
    use_agent: false
  snapshots:
    check_interval_seconds: 1
    block_interval: 3600
    run_once: false
    rclone:
      version: "1.65.2"
      env:
        RCLONE_CONFIG_MYS3_TYPE: s3
        RCLONE_CONFIG_MYS3_PROVIDER: Digitalocean
        RCLONE_CONFIG_MYS3_ACL: private
        RCLONE_CONFIG_MYS3_ENDPOINT: $S3_ENDPOINT_URL
        RCLONE_CONFIG_MYS3_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        RCLONE_CONFIG_MYS3_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      cmd_template: >-
        sync
        --fast-list
        {{ .DataDir }} mys3:/{{ .UploadPathPrefix }}
        --transfers=100
        --checkers=200
        --exclude=/nodekey
        --exclude=/key
        --exclude=/discovery-secret

targets:
  ssh:
    - alias: "geth"
      host: "167.99.40.39"
      user: "devops"
      port: 22
      data_dir: /data/geth/geth
      upload_prefix: ethpandaops-ethereum-node-snapshots/holesky/geth/latest/
    - alias: "nethermind"
      host: "167.99.32.248"
      user: "devops"
      port: 22
      data_dir: /data/nethermind/nethermind_db
      upload_prefix: ethpandaops-ethereum-node-snapshots/holesky/nethermind/latest/
    - alias: "besu"
      host: "134.209.192.216"
      user: "devops"
      port: 22
      data_dir: /data/besu
      upload_prefix: ethpandaops-ethereum-node-snapshots/holesky/besu/latest/
    - alias: "erigon"
      host: "152.42.136.43"
      user: "devops"
      port: 22
      data_dir: /data/erigon
      upload_prefix: ethpandaops-ethereum-node-snapshots/holesky/erigon/latest/
    - alias: "reth"
      host: "134.209.207.122"
      user: "devops"
      port: 22
      data_dir: /data/reth
      upload_prefix: ethpandaops-ethereum-node-snapshots/holesky/reth/latest/
